// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: scrp/scrp.proto

package scrp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SCRPService_ResolveConflict_FullMethodName = "/scrp.SCRPService/ResolveConflict"
)

// SCRPServiceClient is the client API for SCRPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SCRPServiceClient interface {
	ResolveConflict(ctx context.Context, in *ResolveConflictRequest, opts ...grpc.CallOption) (*ResolveConflictResponse, error)
}

type sCRPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSCRPServiceClient(cc grpc.ClientConnInterface) SCRPServiceClient {
	return &sCRPServiceClient{cc}
}

func (c *sCRPServiceClient) ResolveConflict(ctx context.Context, in *ResolveConflictRequest, opts ...grpc.CallOption) (*ResolveConflictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveConflictResponse)
	err := c.cc.Invoke(ctx, SCRPService_ResolveConflict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SCRPServiceServer is the server API for SCRPService service.
// All implementations must embed UnimplementedSCRPServiceServer
// for forward compatibility.
type SCRPServiceServer interface {
	ResolveConflict(context.Context, *ResolveConflictRequest) (*ResolveConflictResponse, error)
	mustEmbedUnimplementedSCRPServiceServer()
}

// UnimplementedSCRPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSCRPServiceServer struct{}

func (UnimplementedSCRPServiceServer) ResolveConflict(context.Context, *ResolveConflictRequest) (*ResolveConflictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveConflict not implemented")
}
func (UnimplementedSCRPServiceServer) mustEmbedUnimplementedSCRPServiceServer() {}
func (UnimplementedSCRPServiceServer) testEmbeddedByValue()                     {}

// UnsafeSCRPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SCRPServiceServer will
// result in compilation errors.
type UnsafeSCRPServiceServer interface {
	mustEmbedUnimplementedSCRPServiceServer()
}

func RegisterSCRPServiceServer(s grpc.ServiceRegistrar, srv SCRPServiceServer) {
	// If the following call panics, it indicates UnimplementedSCRPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SCRPService_ServiceDesc, srv)
}

func _SCRPService_ResolveConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveConflictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SCRPServiceServer).ResolveConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SCRPService_ResolveConflict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SCRPServiceServer).ResolveConflict(ctx, req.(*ResolveConflictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SCRPService_ServiceDesc is the grpc.ServiceDesc for SCRPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SCRPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scrp.SCRPService",
	HandlerType: (*SCRPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveConflict",
			Handler:    _SCRPService_ResolveConflict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scrp/scrp.proto",
}
