// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: scrp/scrp.proto

package scrp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WaypointProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Z             float64                `protobuf:"fixed64,4,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaypointProto) Reset() {
	*x = WaypointProto{}
	mi := &file_scrp_scrp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaypointProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaypointProto) ProtoMessage() {}

func (x *WaypointProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaypointProto.ProtoReflect.Descriptor instead.
func (*WaypointProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{0}
}

func (x *WaypointProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WaypointProto) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WaypointProto) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WaypointProto) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type SegmentProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PStart        *WaypointProto         `protobuf:"bytes,1,opt,name=p_start,json=pStart,proto3" json:"p_start,omitempty"`
	PEnd          *WaypointProto         `protobuf:"bytes,2,opt,name=p_end,json=pEnd,proto3" json:"p_end,omitempty"`
	Length        float64                `protobuf:"fixed64,3,opt,name=length,proto3" json:"length,omitempty"`
	VMin          float64                `protobuf:"fixed64,4,opt,name=v_min,json=vMin,proto3" json:"v_min,omitempty"`
	VMax          float64                `protobuf:"fixed64,5,opt,name=v_max,json=vMax,proto3" json:"v_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SegmentProto) Reset() {
	*x = SegmentProto{}
	mi := &file_scrp_scrp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentProto) ProtoMessage() {}

func (x *SegmentProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentProto.ProtoReflect.Descriptor instead.
func (*SegmentProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{1}
}

func (x *SegmentProto) GetPStart() *WaypointProto {
	if x != nil {
		return x.PStart
	}
	return nil
}

func (x *SegmentProto) GetPEnd() *WaypointProto {
	if x != nil {
		return x.PEnd
	}
	return nil
}

func (x *SegmentProto) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *SegmentProto) GetVMin() float64 {
	if x != nil {
		return x.VMin
	}
	return 0
}

func (x *SegmentProto) GetVMax() float64 {
	if x != nil {
		return x.VMax
	}
	return 0
}

type LaneProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Waypoints     []*WaypointProto       `protobuf:"bytes,2,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	Segments      []*SegmentProto        `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaneProto) Reset() {
	*x = LaneProto{}
	mi := &file_scrp_scrp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaneProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaneProto) ProtoMessage() {}

func (x *LaneProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaneProto.ProtoReflect.Descriptor instead.
func (*LaneProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{2}
}

func (x *LaneProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LaneProto) GetWaypoints() []*WaypointProto {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

func (x *LaneProto) GetSegments() []*SegmentProto {
	if x != nil {
		return x.Segments
	}
	return nil
}

type WaypointTimeEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Waypoint      *WaypointProto         `protobuf:"bytes,1,opt,name=waypoint,proto3" json:"waypoint,omitempty"`
	Time          float64                `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaypointTimeEntryProto) Reset() {
	*x = WaypointTimeEntryProto{}
	mi := &file_scrp_scrp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaypointTimeEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaypointTimeEntryProto) ProtoMessage() {}

func (x *WaypointTimeEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaypointTimeEntryProto.ProtoReflect.Descriptor instead.
func (*WaypointTimeEntryProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{3}
}

func (x *WaypointTimeEntryProto) GetWaypoint() *WaypointProto {
	if x != nil {
		return x.Waypoint
	}
	return nil
}

func (x *WaypointTimeEntryProto) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ApprovedPlanProto struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	DroneId       string                    `protobuf:"bytes,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	UavType       string                    `protobuf:"bytes,2,opt,name=uav_type,json=uavType,proto3" json:"uav_type,omitempty"`
	Lane          *LaneProto                `protobuf:"bytes,3,opt,name=lane,proto3" json:"lane,omitempty"`
	VWaypoints    []float64                 `protobuf:"fixed64,4,rep,packed,name=v_waypoints,json=vWaypoints,proto3" json:"v_waypoints,omitempty"`
	TLand         float64                   `protobuf:"fixed64,5,opt,name=t_land,json=tLand,proto3" json:"t_land,omitempty"`
	PadId         string                    `protobuf:"bytes,6,opt,name=pad_id,json=padId,proto3" json:"pad_id,omitempty"`
	SlotIndex     int32                     `protobuf:"varint,7,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	Status        string                    `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	WaypointTimes []*WaypointTimeEntryProto `protobuf:"bytes,10,rep,name=waypoint_times,json=waypointTimes,proto3" json:"waypoint_times,omitempty"`
	Algorithm     string                    `protobuf:"bytes,11,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	ExpiresAt     float64                   `protobuf:"fixed64,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovedPlanProto) Reset() {
	*x = ApprovedPlanProto{}
	mi := &file_scrp_scrp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovedPlanProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovedPlanProto) ProtoMessage() {}

func (x *ApprovedPlanProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovedPlanProto.ProtoReflect.Descriptor instead.
func (*ApprovedPlanProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{4}
}

func (x *ApprovedPlanProto) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *ApprovedPlanProto) GetUavType() string {
	if x != nil {
		return x.UavType
	}
	return ""
}

func (x *ApprovedPlanProto) GetLane() *LaneProto {
	if x != nil {
		return x.Lane
	}
	return nil
}

func (x *ApprovedPlanProto) GetVWaypoints() []float64 {
	if x != nil {
		return x.VWaypoints
	}
	return nil
}

func (x *ApprovedPlanProto) GetTLand() float64 {
	if x != nil {
		return x.TLand
	}
	return 0
}

func (x *ApprovedPlanProto) GetPadId() string {
	if x != nil {
		return x.PadId
	}
	return ""
}

func (x *ApprovedPlanProto) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ApprovedPlanProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApprovedPlanProto) GetWaypointTimes() []*WaypointTimeEntryProto {
	if x != nil {
		return x.WaypointTimes
	}
	return nil
}

func (x *ApprovedPlanProto) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *ApprovedPlanProto) GetExpiresAt() float64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type PadProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CompatibleTypes []string               `protobuf:"bytes,2,rep,name=compatible_types,json=compatibleTypes,proto3" json:"compatible_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PadProto) Reset() {
	*x = PadProto{}
	mi := &file_scrp_scrp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PadProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PadProto) ProtoMessage() {}

func (x *PadProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PadProto.ProtoReflect.Descriptor instead.
func (*PadProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{5}
}

func (x *PadProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PadProto) GetCompatibleTypes() []string {
	if x != nil {
		return x.CompatibleTypes
	}
	return nil
}

type SlotEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PadId         string                 `protobuf:"bytes,1,opt,name=pad_id,json=padId,proto3" json:"pad_id,omitempty"`
	SlotIndex     int32                  `protobuf:"varint,2,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	DroneId       string                 `protobuf:"bytes,3,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotEntryProto) Reset() {
	*x = SlotEntryProto{}
	mi := &file_scrp_scrp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotEntryProto) ProtoMessage() {}

func (x *SlotEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotEntryProto.ProtoReflect.Descriptor instead.
func (*SlotEntryProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{6}
}

func (x *SlotEntryProto) GetPadId() string {
	if x != nil {
		return x.PadId
	}
	return ""
}

func (x *SlotEntryProto) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *SlotEntryProto) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *SlotEntryProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VertiportStateProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VertiportId   string                 `protobuf:"bytes,1,opt,name=vertiport_id,json=vertiportId,proto3" json:"vertiport_id,omitempty"`
	Pads          []*PadProto            `protobuf:"bytes,2,rep,name=pads,proto3" json:"pads,omitempty"`
	SlotDuration  float64                `protobuf:"fixed64,3,opt,name=slot_duration,json=slotDuration,proto3" json:"slot_duration,omitempty"`
	Slots         []*SlotEntryProto      `protobuf:"bytes,4,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VertiportStateProto) Reset() {
	*x = VertiportStateProto{}
	mi := &file_scrp_scrp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VertiportStateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertiportStateProto) ProtoMessage() {}

func (x *VertiportStateProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertiportStateProto.ProtoReflect.Descriptor instead.
func (*VertiportStateProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{7}
}

func (x *VertiportStateProto) GetVertiportId() string {
	if x != nil {
		return x.VertiportId
	}
	return ""
}

func (x *VertiportStateProto) GetPads() []*PadProto {
	if x != nil {
		return x.Pads
	}
	return nil
}

func (x *VertiportStateProto) GetSlotDuration() float64 {
	if x != nil {
		return x.SlotDuration
	}
	return 0
}

func (x *VertiportStateProto) GetSlots() []*SlotEntryProto {
	if x != nil {
		return x.Slots
	}
	return nil
}

type MsdEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UavTypeI      string                 `protobuf:"bytes,1,opt,name=uav_type_i,json=uavTypeI,proto3" json:"uav_type_i,omitempty"`
	UavTypeJ      string                 `protobuf:"bytes,2,opt,name=uav_type_j,json=uavTypeJ,proto3" json:"uav_type_j,omitempty"`
	Msd           float64                `protobuf:"fixed64,3,opt,name=msd,proto3" json:"msd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsdEntryProto) Reset() {
	*x = MsdEntryProto{}
	mi := &file_scrp_scrp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsdEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsdEntryProto) ProtoMessage() {}

func (x *MsdEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsdEntryProto.ProtoReflect.Descriptor instead.
func (*MsdEntryProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{8}
}

func (x *MsdEntryProto) GetUavTypeI() string {
	if x != nil {
		return x.UavTypeI
	}
	return ""
}

func (x *MsdEntryProto) GetUavTypeJ() string {
	if x != nil {
		return x.UavTypeJ
	}
	return ""
}

func (x *MsdEntryProto) GetMsd() float64 {
	if x != nil {
		return x.Msd
	}
	return 0
}

type BodyLengthEntryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UavType       string                 `protobuf:"bytes,1,opt,name=uav_type,json=uavType,proto3" json:"uav_type,omitempty"`
	LengthM       float64                `protobuf:"fixed64,2,opt,name=length_m,json=lengthM,proto3" json:"length_m,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BodyLengthEntryProto) Reset() {
	*x = BodyLengthEntryProto{}
	mi := &file_scrp_scrp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BodyLengthEntryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyLengthEntryProto) ProtoMessage() {}

func (x *BodyLengthEntryProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyLengthEntryProto.ProtoReflect.Descriptor instead.
func (*BodyLengthEntryProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{9}
}

func (x *BodyLengthEntryProto) GetUavType() string {
	if x != nil {
		return x.UavType
	}
	return ""
}

func (x *BodyLengthEntryProto) GetLengthM() float64 {
	if x != nil {
		return x.LengthM
	}
	return 0
}

type SystemStateProto struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	ApprovedPlans  []*ApprovedPlanProto    `protobuf:"bytes,1,rep,name=approved_plans,json=approvedPlans,proto3" json:"approved_plans,omitempty"`
	VertiportState *VertiportStateProto    `protobuf:"bytes,2,opt,name=vertiport_state,json=vertiportState,proto3" json:"vertiport_state,omitempty"`
	TNow           float64                 `protobuf:"fixed64,3,opt,name=t_now,json=tNow,proto3" json:"t_now,omitempty"`
	MsdMatrix      []*MsdEntryProto        `protobuf:"bytes,4,rep,name=msd_matrix,json=msdMatrix,proto3" json:"msd_matrix,omitempty"`
	BodyLength     []*BodyLengthEntryProto `protobuf:"bytes,5,rep,name=body_length,json=bodyLength,proto3" json:"body_length,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SystemStateProto) Reset() {
	*x = SystemStateProto{}
	mi := &file_scrp_scrp_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStateProto) ProtoMessage() {}

func (x *SystemStateProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStateProto.ProtoReflect.Descriptor instead.
func (*SystemStateProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{10}
}

func (x *SystemStateProto) GetApprovedPlans() []*ApprovedPlanProto {
	if x != nil {
		return x.ApprovedPlans
	}
	return nil
}

func (x *SystemStateProto) GetVertiportState() *VertiportStateProto {
	if x != nil {
		return x.VertiportState
	}
	return nil
}

func (x *SystemStateProto) GetTNow() float64 {
	if x != nil {
		return x.TNow
	}
	return 0
}

func (x *SystemStateProto) GetMsdMatrix() []*MsdEntryProto {
	if x != nil {
		return x.MsdMatrix
	}
	return nil
}

func (x *SystemStateProto) GetBodyLength() []*BodyLengthEntryProto {
	if x != nil {
		return x.BodyLength
	}
	return nil
}

type WaypointTimeResultProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WaypointId    string                 `protobuf:"bytes,1,opt,name=waypoint_id,json=waypointId,proto3" json:"waypoint_id,omitempty"`
	Time          float64                `protobuf:"fixed64,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaypointTimeResultProto) Reset() {
	*x = WaypointTimeResultProto{}
	mi := &file_scrp_scrp_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaypointTimeResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaypointTimeResultProto) ProtoMessage() {}

func (x *WaypointTimeResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaypointTimeResultProto.ProtoReflect.Descriptor instead.
func (*WaypointTimeResultProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{11}
}

func (x *WaypointTimeResultProto) GetWaypointId() string {
	if x != nil {
		return x.WaypointId
	}
	return ""
}

func (x *WaypointTimeResultProto) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ApproveResultProto struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	Status         string                     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TDepStar       float64                    `protobuf:"fixed64,2,opt,name=t_dep_star,json=tDepStar,proto3" json:"t_dep_star,omitempty"`
	TLandAssigned  float64                    `protobuf:"fixed64,3,opt,name=t_land_assigned,json=tLandAssigned,proto3" json:"t_land_assigned,omitempty"`
	PadId          string                     `protobuf:"bytes,4,opt,name=pad_id,json=padId,proto3" json:"pad_id,omitempty"`
	SlotIndex      int32                      `protobuf:"varint,5,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	WaypointTimes  []*WaypointTimeResultProto `protobuf:"bytes,6,rep,name=waypoint_times,json=waypointTimes,proto3" json:"waypoint_times,omitempty"`
	ExpiresAt      float64                    `protobuf:"fixed64,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	DelaySeconds   float64                    `protobuf:"fixed64,8,opt,name=delay_seconds,json=delaySeconds,proto3" json:"delay_seconds,omitempty"`
	DelaySource    string                     `protobuf:"bytes,9,opt,name=delay_source,json=delaySource,proto3" json:"delay_source,omitempty"`
	EnergyEstimate float64                    `protobuf:"fixed64,10,opt,name=energy_estimate,json=energyEstimate,proto3" json:"energy_estimate,omitempty"`
	SocMeaning     float64                    `protobuf:"fixed64,11,opt,name=soc_meaning,json=socMeaning,proto3" json:"soc_meaning,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApproveResultProto) Reset() {
	*x = ApproveResultProto{}
	mi := &file_scrp_scrp_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveResultProto) ProtoMessage() {}

func (x *ApproveResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveResultProto.ProtoReflect.Descriptor instead.
func (*ApproveResultProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{12}
}

func (x *ApproveResultProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApproveResultProto) GetTDepStar() float64 {
	if x != nil {
		return x.TDepStar
	}
	return 0
}

func (x *ApproveResultProto) GetTLandAssigned() float64 {
	if x != nil {
		return x.TLandAssigned
	}
	return 0
}

func (x *ApproveResultProto) GetPadId() string {
	if x != nil {
		return x.PadId
	}
	return ""
}

func (x *ApproveResultProto) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *ApproveResultProto) GetWaypointTimes() []*WaypointTimeResultProto {
	if x != nil {
		return x.WaypointTimes
	}
	return nil
}

func (x *ApproveResultProto) GetExpiresAt() float64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ApproveResultProto) GetDelaySeconds() float64 {
	if x != nil {
		return x.DelaySeconds
	}
	return 0
}

func (x *ApproveResultProto) GetDelaySource() string {
	if x != nil {
		return x.DelaySource
	}
	return ""
}

func (x *ApproveResultProto) GetEnergyEstimate() float64 {
	if x != nil {
		return x.EnergyEstimate
	}
	return 0
}

func (x *ApproveResultProto) GetSocMeaning() float64 {
	if x != nil {
		return x.SocMeaning
	}
	return 0
}

type RejectResultProto struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Status              string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reason              string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	EarliestPossible    float64                `protobuf:"fixed64,3,opt,name=earliest_possible,json=earliestPossible,proto3" json:"earliest_possible,omitempty"`
	HasEarliestPossible bool                   `protobuf:"varint,4,opt,name=has_earliest_possible,json=hasEarliestPossible,proto3" json:"has_earliest_possible,omitempty"`
	Detail              string                 `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RejectResultProto) Reset() {
	*x = RejectResultProto{}
	mi := &file_scrp_scrp_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectResultProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectResultProto) ProtoMessage() {}

func (x *RejectResultProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectResultProto.ProtoReflect.Descriptor instead.
func (*RejectResultProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{13}
}

func (x *RejectResultProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RejectResultProto) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectResultProto) GetEarliestPossible() float64 {
	if x != nil {
		return x.EarliestPossible
	}
	return 0
}

func (x *RejectResultProto) GetHasEarliestPossible() bool {
	if x != nil {
		return x.HasEarliestPossible
	}
	return false
}

func (x *RejectResultProto) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type OperatorFlightRequestProto struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	OperatorId             string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	DroneId                string                 `protobuf:"bytes,2,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Lane                   *LaneProto             `protobuf:"bytes,3,opt,name=lane,proto3" json:"lane,omitempty"`
	VWaypoints             []float64              `protobuf:"fixed64,4,rep,packed,name=v_waypoints,json=vWaypoints,proto3" json:"v_waypoints,omitempty"`
	DestinationVertiportId string                 `protobuf:"bytes,5,opt,name=destination_vertiport_id,json=destinationVertiportId,proto3" json:"destination_vertiport_id,omitempty"`
	TDes                   float64                `protobuf:"fixed64,6,opt,name=t_des,json=tDes,proto3" json:"t_des,omitempty"`
	Priority               int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	UavType                string                 `protobuf:"bytes,8,opt,name=uav_type,json=uavType,proto3" json:"uav_type,omitempty"`
	Soc_0                  float64                `protobuf:"fixed64,9,opt,name=soc_0,json=soc0,proto3" json:"soc_0,omitempty"`
	CBat                   float64                `protobuf:"fixed64,10,opt,name=c_bat,json=cBat,proto3" json:"c_bat,omitempty"`
	PHover                 float64                `protobuf:"fixed64,11,opt,name=p_hover,json=pHover,proto3" json:"p_hover,omitempty"`
	TTakeoff               float64                `protobuf:"fixed64,12,opt,name=t_takeoff,json=tTakeoff,proto3" json:"t_takeoff,omitempty"`
	TLandEstimated         float64                `protobuf:"fixed64,13,opt,name=t_land_estimated,json=tLandEstimated,proto3" json:"t_land_estimated,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OperatorFlightRequestProto) Reset() {
	*x = OperatorFlightRequestProto{}
	mi := &file_scrp_scrp_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatorFlightRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatorFlightRequestProto) ProtoMessage() {}

func (x *OperatorFlightRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperatorFlightRequestProto.ProtoReflect.Descriptor instead.
func (*OperatorFlightRequestProto) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{14}
}

func (x *OperatorFlightRequestProto) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *OperatorFlightRequestProto) GetDroneId() string {
	if x != nil {
		return x.DroneId
	}
	return ""
}

func (x *OperatorFlightRequestProto) GetLane() *LaneProto {
	if x != nil {
		return x.Lane
	}
	return nil
}

func (x *OperatorFlightRequestProto) GetVWaypoints() []float64 {
	if x != nil {
		return x.VWaypoints
	}
	return nil
}

func (x *OperatorFlightRequestProto) GetDestinationVertiportId() string {
	if x != nil {
		return x.DestinationVertiportId
	}
	return ""
}

func (x *OperatorFlightRequestProto) GetTDes() float64 {
	if x != nil {
		return x.TDes
	}
	return 0
}

func (x *OperatorFlightRequestProto) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *OperatorFlightRequestProto) GetUavType() string {
	if x != nil {
		return x.UavType
	}
	return ""
}

func (x *OperatorFlightRequestProto) GetSoc_0() float64 {
	if x != nil {
		return x.Soc_0
	}
	return 0
}

func (x *OperatorFlightRequestProto) GetCBat() float64 {
	if x != nil {
		return x.CBat
	}
	return 0
}

func (x *OperatorFlightRequestProto) GetPHover() float64 {
	if x != nil {
		return x.PHover
	}
	return 0
}

func (x *OperatorFlightRequestProto) GetTTakeoff() float64 {
	if x != nil {
		return x.TTakeoff
	}
	return 0
}

func (x *OperatorFlightRequestProto) GetTLandEstimated() float64 {
	if x != nil {
		return x.TLandEstimated
	}
	return 0
}

type ResolveConflictRequest struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	FlightIntention *OperatorFlightRequestProto `protobuf:"bytes,1,opt,name=flight_intention,json=flightIntention,proto3" json:"flight_intention,omitempty"`
	ApprovedPlans   []*ApprovedPlanProto        `protobuf:"bytes,2,rep,name=approved_plans,json=approvedPlans,proto3" json:"approved_plans,omitempty"`
	VertiportState  *VertiportStateProto        `protobuf:"bytes,3,opt,name=vertiport_state,json=vertiportState,proto3" json:"vertiport_state,omitempty"`
	SystemState     *SystemStateProto           `protobuf:"bytes,4,opt,name=system_state,json=systemState,proto3" json:"system_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResolveConflictRequest) Reset() {
	*x = ResolveConflictRequest{}
	mi := &file_scrp_scrp_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveConflictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConflictRequest) ProtoMessage() {}

func (x *ResolveConflictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConflictRequest.ProtoReflect.Descriptor instead.
func (*ResolveConflictRequest) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{15}
}

func (x *ResolveConflictRequest) GetFlightIntention() *OperatorFlightRequestProto {
	if x != nil {
		return x.FlightIntention
	}
	return nil
}

func (x *ResolveConflictRequest) GetApprovedPlans() []*ApprovedPlanProto {
	if x != nil {
		return x.ApprovedPlans
	}
	return nil
}

func (x *ResolveConflictRequest) GetVertiportState() *VertiportStateProto {
	if x != nil {
		return x.VertiportState
	}
	return nil
}

func (x *ResolveConflictRequest) GetSystemState() *SystemStateProto {
	if x != nil {
		return x.SystemState
	}
	return nil
}

type ResolveConflictResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ResolveConflictResponse_Approve
	//	*ResolveConflictResponse_Reject
	Result        isResolveConflictResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveConflictResponse) Reset() {
	*x = ResolveConflictResponse{}
	mi := &file_scrp_scrp_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveConflictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConflictResponse) ProtoMessage() {}

func (x *ResolveConflictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrp_scrp_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConflictResponse.ProtoReflect.Descriptor instead.
func (*ResolveConflictResponse) Descriptor() ([]byte, []int) {
	return file_scrp_scrp_proto_rawDescGZIP(), []int{16}
}

func (x *ResolveConflictResponse) GetResult() isResolveConflictResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResolveConflictResponse) GetApprove() *ApproveResultProto {
	if x != nil {
		if x, ok := x.Result.(*ResolveConflictResponse_Approve); ok {
			return x.Approve
		}
	}
	return nil
}

func (x *ResolveConflictResponse) GetReject() *RejectResultProto {
	if x != nil {
		if x, ok := x.Result.(*ResolveConflictResponse_Reject); ok {
			return x.Reject
		}
	}
	return nil
}

type isResolveConflictResponse_Result interface {
	isResolveConflictResponse_Result()
}

type ResolveConflictResponse_Approve struct {
	Approve *ApproveResultProto `protobuf:"bytes,1,opt,name=approve,proto3,oneof"`
}

type ResolveConflictResponse_Reject struct {
	Reject *RejectResultProto `protobuf:"bytes,2,opt,name=reject,proto3,oneof"`
}

func (*ResolveConflictResponse_Approve) isResolveConflictResponse_Result() {}

func (*ResolveConflictResponse_Reject) isResolveConflictResponse_Result() {}

var File_scrp_scrp_proto protoreflect.FileDescriptor

const file_scrp_scrp_proto_rawDesc = "" +
	"\n" +
	"\x0fscrp/scrp.proto\x12\x04scrp\"I\n" +
	"\rWaypointProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\f\n" +
	"\x01z\x18\x04 \x01(\x01R\x01z\"\xa8\x01\n" +
	"\fSegmentProto\x12,\n" +
	"\ap_start\x18\x01 \x01(\v2\x13.scrp.WaypointProtoR\x06pStart\x12(\n" +
	"\x05p_end\x18\x02 \x01(\v2\x13.scrp.WaypointProtoR\x04pEnd\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x01R\x06length\x12\x13\n" +
	"\x05v_min\x18\x04 \x01(\x01R\x04vMin\x12\x13\n" +
	"\x05v_max\x18\x05 \x01(\x01R\x04vMax\"~\n" +
	"\tLaneProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\twaypoints\x18\x02 \x03(\v2\x13.scrp.WaypointProtoR\twaypoints\x12.\n" +
	"\bsegments\x18\x03 \x03(\v2\x12.scrp.SegmentProtoR\bsegments\"]\n" +
	"\x16WaypointTimeEntryProto\x12/\n" +
	"\bwaypoint\x18\x01 \x01(\v2\x13.scrp.WaypointProtoR\bwaypoint\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x01R\x04time\"\xf6\x02\n" +
	"\x11ApprovedPlanProto\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\tR\adroneId\x12\x19\n" +
	"\buav_type\x18\x02 \x01(\tR\auavType\x12#\n" +
	"\x04lane\x18\x03 \x01(\v2\x0f.scrp.LaneProtoR\x04lane\x12\x1f\n" +
	"\vv_waypoints\x18\x04 \x03(\x01R\n" +
	"vWaypoints\x12\x15\n" +
	"\x06t_land\x18\x05 \x01(\x01R\x05tLand\x12\x15\n" +
	"\x06pad_id\x18\x06 \x01(\tR\x05padId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\a \x01(\x05R\tslotIndex\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12C\n" +
	"\x0ewaypoint_times\x18\n" +
	" \x03(\v2\x1c.scrp.WaypointTimeEntryProtoR\rwaypointTimes\x12\x1c\n" +
	"\talgorithm\x18\v \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"expires_at\x18\f \x01(\x01R\texpiresAt\"E\n" +
	"\bPadProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10compatible_types\x18\x02 \x03(\tR\x0fcompatibleTypes\"y\n" +
	"\x0eSlotEntryProto\x12\x15\n" +
	"\x06pad_id\x18\x01 \x01(\tR\x05padId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x02 \x01(\x05R\tslotIndex\x12\x19\n" +
	"\bdrone_id\x18\x03 \x01(\tR\adroneId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xad\x01\n" +
	"\x13VertiportStateProto\x12!\n" +
	"\fvertiport_id\x18\x01 \x01(\tR\vvertiportId\x12\"\n" +
	"\x04pads\x18\x02 \x03(\v2\x0e.scrp.PadProtoR\x04pads\x12#\n" +
	"\rslot_duration\x18\x03 \x01(\x01R\fslotDuration\x12*\n" +
	"\x05slots\x18\x04 \x03(\v2\x14.scrp.SlotEntryProtoR\x05slots\"]\n" +
	"\rMsdEntryProto\x12\x1c\n" +
	"\n" +
	"uav_type_i\x18\x01 \x01(\tR\buavTypeI\x12\x1c\n" +
	"\n" +
	"uav_type_j\x18\x02 \x01(\tR\buavTypeJ\x12\x10\n" +
	"\x03msd\x18\x03 \x01(\x01R\x03msd\"L\n" +
	"\x14BodyLengthEntryProto\x12\x19\n" +
	"\buav_type\x18\x01 \x01(\tR\auavType\x12\x19\n" +
	"\blength_m\x18\x02 \x01(\x01R\alengthM\"\x9c\x02\n" +
	"\x10SystemStateProto\x12>\n" +
	"\x0eapproved_plans\x18\x01 \x03(\v2\x17.scrp.ApprovedPlanProtoR\rapprovedPlans\x12B\n" +
	"\x0fvertiport_state\x18\x02 \x01(\v2\x19.scrp.VertiportStateProtoR\x0evertiportState\x12\x13\n" +
	"\x05t_now\x18\x03 \x01(\x01R\x04tNow\x122\n" +
	"\n" +
	"msd_matrix\x18\x04 \x03(\v2\x13.scrp.MsdEntryProtoR\tmsdMatrix\x12;\n" +
	"\vbody_length\x18\x05 \x03(\v2\x1a.scrp.BodyLengthEntryProtoR\n" +
	"bodyLength\"N\n" +
	"\x17WaypointTimeResultProto\x12\x1f\n" +
	"\vwaypoint_id\x18\x01 \x01(\tR\n" +
	"waypointId\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x01R\x04time\"\x9f\x03\n" +
	"\x12ApproveResultProto\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\n" +
	"t_dep_star\x18\x02 \x01(\x01R\btDepStar\x12&\n" +
	"\x0ft_land_assigned\x18\x03 \x01(\x01R\rtLandAssigned\x12\x15\n" +
	"\x06pad_id\x18\x04 \x01(\tR\x05padId\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x05 \x01(\x05R\tslotIndex\x12D\n" +
	"\x0ewaypoint_times\x18\x06 \x03(\v2\x1d.scrp.WaypointTimeResultProtoR\rwaypointTimes\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\x01R\texpiresAt\x12#\n" +
	"\rdelay_seconds\x18\b \x01(\x01R\fdelaySeconds\x12!\n" +
	"\fdelay_source\x18\t \x01(\tR\vdelaySource\x12'\n" +
	"\x0fenergy_estimate\x18\n" +
	" \x01(\x01R\x0eenergyEstimate\x12\x1f\n" +
	"\vsoc_meaning\x18\v \x01(\x01R\n" +
	"socMeaning\"\xbc\x01\n" +
	"\x11RejectResultProto\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12+\n" +
	"\x11earliest_possible\x18\x03 \x01(\x01R\x10earliestPossible\x122\n" +
	"\x15has_earliest_possible\x18\x04 \x01(\bR\x13hasEarliestPossible\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\"\xae\x03\n" +
	"\x1aOperatorFlightRequestProto\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\x12\x19\n" +
	"\bdrone_id\x18\x02 \x01(\tR\adroneId\x12#\n" +
	"\x04lane\x18\x03 \x01(\v2\x0f.scrp.LaneProtoR\x04lane\x12\x1f\n" +
	"\vv_waypoints\x18\x04 \x03(\x01R\n" +
	"vWaypoints\x128\n" +
	"\x18destination_vertiport_id\x18\x05 \x01(\tR\x16destinationVertiportId\x12\x13\n" +
	"\x05t_des\x18\x06 \x01(\x01R\x04tDes\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x19\n" +
	"\buav_type\x18\b \x01(\tR\auavType\x12\x13\n" +
	"\x05soc_0\x18\t \x01(\x01R\x04soc0\x12\x13\n" +
	"\x05c_bat\x18\n" +
	" \x01(\x01R\x04cBat\x12\x17\n" +
	"\ap_hover\x18\v \x01(\x01R\x06pHover\x12\x1b\n" +
	"\tt_takeoff\x18\f \x01(\x01R\btTakeoff\x12(\n" +
	"\x10t_land_estimated\x18\r \x01(\x01R\x0etLandEstimated\"\xa4\x02\n" +
	"\x16ResolveConflictRequest\x12K\n" +
	"\x10flight_intention\x18\x01 \x01(\v2 .scrp.OperatorFlightRequestProtoR\x0fflightIntention\x12>\n" +
	"\x0eapproved_plans\x18\x02 \x03(\v2\x17.scrp.ApprovedPlanProtoR\rapprovedPlans\x12B\n" +
	"\x0fvertiport_state\x18\x03 \x01(\v2\x19.scrp.VertiportStateProtoR\x0evertiportState\x129\n" +
	"\fsystem_state\x18\x04 \x01(\v2\x16.scrp.SystemStateProtoR\vsystemState\"\x8c\x01\n" +
	"\x17ResolveConflictResponse\x124\n" +
	"\aapprove\x18\x01 \x01(\v2\x18.scrp.ApproveResultProtoH\x00R\aapprove\x121\n" +
	"\x06reject\x18\x02 \x01(\v2\x17.scrp.RejectResultProtoH\x00R\x06rejectB\b\n" +
	"\x06result2]\n" +
	"\vSCRPService\x12N\n" +
	"\x0fResolveConflict\x12\x1c.scrp.ResolveConflictRequest\x1a\x1d.scrp.ResolveConflictResponseB$Z\"github.com/utm/backend/pkg/pb/scrpb\x06proto3"

var (
	file_scrp_scrp_proto_rawDescOnce sync.Once
	file_scrp_scrp_proto_rawDescData []byte
)

func file_scrp_scrp_proto_rawDescGZIP() []byte {
	file_scrp_scrp_proto_rawDescOnce.Do(func() {
		file_scrp_scrp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scrp_scrp_proto_rawDesc), len(file_scrp_scrp_proto_rawDesc)))
	})
	return file_scrp_scrp_proto_rawDescData
}

var file_scrp_scrp_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_scrp_scrp_proto_goTypes = []any{
	(*WaypointProto)(nil),              // 0: scrp.WaypointProto
	(*SegmentProto)(nil),               // 1: scrp.SegmentProto
	(*LaneProto)(nil),                  // 2: scrp.LaneProto
	(*WaypointTimeEntryProto)(nil),     // 3: scrp.WaypointTimeEntryProto
	(*ApprovedPlanProto)(nil),          // 4: scrp.ApprovedPlanProto
	(*PadProto)(nil),                   // 5: scrp.PadProto
	(*SlotEntryProto)(nil),             // 6: scrp.SlotEntryProto
	(*VertiportStateProto)(nil),        // 7: scrp.VertiportStateProto
	(*MsdEntryProto)(nil),              // 8: scrp.MsdEntryProto
	(*BodyLengthEntryProto)(nil),       // 9: scrp.BodyLengthEntryProto
	(*SystemStateProto)(nil),           // 10: scrp.SystemStateProto
	(*WaypointTimeResultProto)(nil),    // 11: scrp.WaypointTimeResultProto
	(*ApproveResultProto)(nil),         // 12: scrp.ApproveResultProto
	(*RejectResultProto)(nil),          // 13: scrp.RejectResultProto
	(*OperatorFlightRequestProto)(nil), // 14: scrp.OperatorFlightRequestProto
	(*ResolveConflictRequest)(nil),     // 15: scrp.ResolveConflictRequest
	(*ResolveConflictResponse)(nil),    // 16: scrp.ResolveConflictResponse
}
var file_scrp_scrp_proto_depIdxs = []int32{
	0,  // 0: scrp.SegmentProto.p_start:type_name -> scrp.WaypointProto
	0,  // 1: scrp.SegmentProto.p_end:type_name -> scrp.WaypointProto
	0,  // 2: scrp.LaneProto.waypoints:type_name -> scrp.WaypointProto
	1,  // 3: scrp.LaneProto.segments:type_name -> scrp.SegmentProto
	0,  // 4: scrp.WaypointTimeEntryProto.waypoint:type_name -> scrp.WaypointProto
	2,  // 5: scrp.ApprovedPlanProto.lane:type_name -> scrp.LaneProto
	3,  // 6: scrp.ApprovedPlanProto.waypoint_times:type_name -> scrp.WaypointTimeEntryProto
	5,  // 7: scrp.VertiportStateProto.pads:type_name -> scrp.PadProto
	6,  // 8: scrp.VertiportStateProto.slots:type_name -> scrp.SlotEntryProto
	4,  // 9: scrp.SystemStateProto.approved_plans:type_name -> scrp.ApprovedPlanProto
	7,  // 10: scrp.SystemStateProto.vertiport_state:type_name -> scrp.VertiportStateProto
	8,  // 11: scrp.SystemStateProto.msd_matrix:type_name -> scrp.MsdEntryProto
	9,  // 12: scrp.SystemStateProto.body_length:type_name -> scrp.BodyLengthEntryProto
	11, // 13: scrp.ApproveResultProto.waypoint_times:type_name -> scrp.WaypointTimeResultProto
	2,  // 14: scrp.OperatorFlightRequestProto.lane:type_name -> scrp.LaneProto
	14, // 15: scrp.ResolveConflictRequest.flight_intention:type_name -> scrp.OperatorFlightRequestProto
	4,  // 16: scrp.ResolveConflictRequest.approved_plans:type_name -> scrp.ApprovedPlanProto
	7,  // 17: scrp.ResolveConflictRequest.vertiport_state:type_name -> scrp.VertiportStateProto
	10, // 18: scrp.ResolveConflictRequest.system_state:type_name -> scrp.SystemStateProto
	12, // 19: scrp.ResolveConflictResponse.approve:type_name -> scrp.ApproveResultProto
	13, // 20: scrp.ResolveConflictResponse.reject:type_name -> scrp.RejectResultProto
	15, // 21: scrp.SCRPService.ResolveConflict:input_type -> scrp.ResolveConflictRequest
	16, // 22: scrp.SCRPService.ResolveConflict:output_type -> scrp.ResolveConflictResponse
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_scrp_scrp_proto_init() }
func file_scrp_scrp_proto_init() {
	if File_scrp_scrp_proto != nil {
		return
	}
	file_scrp_scrp_proto_msgTypes[16].OneofWrappers = []any{
		(*ResolveConflictResponse_Approve)(nil),
		(*ResolveConflictResponse_Reject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scrp_scrp_proto_rawDesc), len(file_scrp_scrp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scrp_scrp_proto_goTypes,
		DependencyIndexes: file_scrp_scrp_proto_depIdxs,
		MessageInfos:      file_scrp_scrp_proto_msgTypes,
	}.Build()
	File_scrp_scrp_proto = out.File
	file_scrp_scrp_proto_goTypes = nil
	file_scrp_scrp_proto_depIdxs = nil
}
