// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: rtk_station/v1/rtk_station.proto

package rtkpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RTKStationService_CreateStation_FullMethodName = "/rtk_station.v1.RTKStationService/CreateStation"
	RTKStationService_GetStation_FullMethodName    = "/rtk_station.v1.RTKStationService/GetStation"
	RTKStationService_UpdateStation_FullMethodName = "/rtk_station.v1.RTKStationService/UpdateStation"
	RTKStationService_DeleteStation_FullMethodName = "/rtk_station.v1.RTKStationService/DeleteStation"
	RTKStationService_ListStations_FullMethodName  = "/rtk_station.v1.RTKStationService/ListStations"
	RTKStationService_GetSummary_FullMethodName    = "/rtk_station.v1.RTKStationService/GetSummary"
)

// RTKStationServiceClient is the client API for RTKStationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RTKStationServiceClient interface {
	CreateStation(ctx context.Context, in *CreateStationRequest, opts ...grpc.CallOption) (*CreateStationResponse, error)
	GetStation(ctx context.Context, in *GetStationRequest, opts ...grpc.CallOption) (*GetStationResponse, error)
	UpdateStation(ctx context.Context, in *UpdateStationRequest, opts ...grpc.CallOption) (*UpdateStationResponse, error)
	DeleteStation(ctx context.Context, in *DeleteStationRequest, opts ...grpc.CallOption) (*DeleteStationResponse, error)
	ListStations(ctx context.Context, in *ListStationsRequest, opts ...grpc.CallOption) (*ListStationsResponse, error)
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*StationSummary, error)
}

type rTKStationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRTKStationServiceClient(cc grpc.ClientConnInterface) RTKStationServiceClient {
	return &rTKStationServiceClient{cc}
}

func (c *rTKStationServiceClient) CreateStation(ctx context.Context, in *CreateStationRequest, opts ...grpc.CallOption) (*CreateStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStationResponse)
	err := c.cc.Invoke(ctx, RTKStationService_CreateStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTKStationServiceClient) GetStation(ctx context.Context, in *GetStationRequest, opts ...grpc.CallOption) (*GetStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStationResponse)
	err := c.cc.Invoke(ctx, RTKStationService_GetStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTKStationServiceClient) UpdateStation(ctx context.Context, in *UpdateStationRequest, opts ...grpc.CallOption) (*UpdateStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStationResponse)
	err := c.cc.Invoke(ctx, RTKStationService_UpdateStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTKStationServiceClient) DeleteStation(ctx context.Context, in *DeleteStationRequest, opts ...grpc.CallOption) (*DeleteStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStationResponse)
	err := c.cc.Invoke(ctx, RTKStationService_DeleteStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTKStationServiceClient) ListStations(ctx context.Context, in *ListStationsRequest, opts ...grpc.CallOption) (*ListStationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStationsResponse)
	err := c.cc.Invoke(ctx, RTKStationService_ListStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rTKStationServiceClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*StationSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StationSummary)
	err := c.cc.Invoke(ctx, RTKStationService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RTKStationServiceServer is the server API for RTKStationService service.
// All implementations must embed UnimplementedRTKStationServiceServer
// for forward compatibility.
type RTKStationServiceServer interface {
	CreateStation(context.Context, *CreateStationRequest) (*CreateStationResponse, error)
	GetStation(context.Context, *GetStationRequest) (*GetStationResponse, error)
	UpdateStation(context.Context, *UpdateStationRequest) (*UpdateStationResponse, error)
	DeleteStation(context.Context, *DeleteStationRequest) (*DeleteStationResponse, error)
	ListStations(context.Context, *ListStationsRequest) (*ListStationsResponse, error)
	GetSummary(context.Context, *GetSummaryRequest) (*StationSummary, error)
	mustEmbedUnimplementedRTKStationServiceServer()
}

// UnimplementedRTKStationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRTKStationServiceServer struct{}

func (UnimplementedRTKStationServiceServer) CreateStation(context.Context, *CreateStationRequest) (*CreateStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStation not implemented")
}
func (UnimplementedRTKStationServiceServer) GetStation(context.Context, *GetStationRequest) (*GetStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStation not implemented")
}
func (UnimplementedRTKStationServiceServer) UpdateStation(context.Context, *UpdateStationRequest) (*UpdateStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStation not implemented")
}
func (UnimplementedRTKStationServiceServer) DeleteStation(context.Context, *DeleteStationRequest) (*DeleteStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStation not implemented")
}
func (UnimplementedRTKStationServiceServer) ListStations(context.Context, *ListStationsRequest) (*ListStationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStations not implemented")
}
func (UnimplementedRTKStationServiceServer) GetSummary(context.Context, *GetSummaryRequest) (*StationSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedRTKStationServiceServer) mustEmbedUnimplementedRTKStationServiceServer() {}
func (UnimplementedRTKStationServiceServer) testEmbeddedByValue()                           {}

// UnsafeRTKStationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RTKStationServiceServer will
// result in compilation errors.
type UnsafeRTKStationServiceServer interface {
	mustEmbedUnimplementedRTKStationServiceServer()
}

func RegisterRTKStationServiceServer(s grpc.ServiceRegistrar, srv RTKStationServiceServer) {
	// If the following call panics, it indicates UnimplementedRTKStationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RTKStationService_ServiceDesc, srv)
}

func _RTKStationService_CreateStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTKStationServiceServer).CreateStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTKStationService_CreateStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTKStationServiceServer).CreateStation(ctx, req.(*CreateStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTKStationService_GetStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTKStationServiceServer).GetStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTKStationService_GetStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTKStationServiceServer).GetStation(ctx, req.(*GetStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTKStationService_UpdateStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTKStationServiceServer).UpdateStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTKStationService_UpdateStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTKStationServiceServer).UpdateStation(ctx, req.(*UpdateStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTKStationService_DeleteStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTKStationServiceServer).DeleteStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTKStationService_DeleteStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTKStationServiceServer).DeleteStation(ctx, req.(*DeleteStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTKStationService_ListStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTKStationServiceServer).ListStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTKStationService_ListStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTKStationServiceServer).ListStations(ctx, req.(*ListStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RTKStationService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RTKStationServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RTKStationService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RTKStationServiceServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RTKStationService_ServiceDesc is the grpc.ServiceDesc for RTKStationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RTKStationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtk_station.v1.RTKStationService",
	HandlerType: (*RTKStationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStation",
			Handler:    _RTKStationService_CreateStation_Handler,
		},
		{
			MethodName: "GetStation",
			Handler:    _RTKStationService_GetStation_Handler,
		},
		{
			MethodName: "UpdateStation",
			Handler:    _RTKStationService_UpdateStation_Handler,
		},
		{
			MethodName: "DeleteStation",
			Handler:    _RTKStationService_DeleteStation_Handler,
		},
		{
			MethodName: "ListStations",
			Handler:    _RTKStationService_ListStations_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _RTKStationService_GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rtk_station/v1/rtk_station.proto",
}
