// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: manage_info/v1/manage_info.proto

package mipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNKNOWN DeviceType = 0
	DeviceType_DEVICE_TYPE_RADAR   DeviceType = 1
	DeviceType_DEVICE_TYPE_TDOA    DeviceType = 2
	DeviceType_DEVICE_TYPE_HUB     DeviceType = 3
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNKNOWN",
		1: "DEVICE_TYPE_RADAR",
		2: "DEVICE_TYPE_TDOA",
		3: "DEVICE_TYPE_HUB",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNKNOWN": 0,
		"DEVICE_TYPE_RADAR":   1,
		"DEVICE_TYPE_TDOA":    2,
		"DEVICE_TYPE_HUB":     3,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_manage_info_v1_manage_info_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_manage_info_v1_manage_info_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{0}
}

type DeviceStatus int32

const (
	DeviceStatus_DEVICE_STATUS_UNKNOWN     DeviceStatus = 0
	DeviceStatus_DEVICE_STATUS_ONLINE      DeviceStatus = 1
	DeviceStatus_DEVICE_STATUS_OFFLINE     DeviceStatus = 2
	DeviceStatus_DEVICE_STATUS_MAINTENANCE DeviceStatus = 3
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "DEVICE_STATUS_UNKNOWN",
		1: "DEVICE_STATUS_ONLINE",
		2: "DEVICE_STATUS_OFFLINE",
		3: "DEVICE_STATUS_MAINTENANCE",
	}
	DeviceStatus_value = map[string]int32{
		"DEVICE_STATUS_UNKNOWN":     0,
		"DEVICE_STATUS_ONLINE":      1,
		"DEVICE_STATUS_OFFLINE":     2,
		"DEVICE_STATUS_MAINTENANCE": 3,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_manage_info_v1_manage_info_proto_enumTypes[1].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_manage_info_v1_manage_info_proto_enumTypes[1]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{1}
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          DeviceType             `protobuf:"varint,3,opt,name=type,proto3,enum=manage_info.v1.DeviceType" json:"type,omitempty"`
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Status        DeviceStatus           `protobuf:"varint,7,opt,name=status,proto3,enum=manage_info.v1.DeviceStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix millis
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNKNOWN
}

func (x *Device) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Device) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Device) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Device) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNKNOWN
}

func (x *Device) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Device) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          DeviceType             `protobuf:"varint,2,opt,name=type,proto3,enum=manage_info.v1.DeviceType" json:"type,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceRequest) Reset() {
	*x = CreateDeviceRequest{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceRequest) ProtoMessage() {}

func (x *CreateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDeviceRequest) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNKNOWN
}

func (x *CreateDeviceRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateDeviceRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateDeviceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceResponse) Reset() {
	*x = CreateDeviceResponse{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceResponse) ProtoMessage() {}

func (x *CreateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceResponse.ProtoReflect.Descriptor instead.
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type UpdateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Status        DeviceStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=manage_info.v1.DeviceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceRequest) Reset() {
	*x = UpdateDeviceRequest{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceRequest) ProtoMessage() {}

func (x *UpdateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeviceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDeviceRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateDeviceRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateDeviceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateDeviceRequest) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNKNOWN
}

type UpdateDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceResponse) Reset() {
	*x = UpdateDeviceResponse{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceResponse) ProtoMessage() {}

func (x *UpdateDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeviceResponse) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type DeleteDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceRequest) Reset() {
	*x = DeleteDeviceRequest{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceRequest) ProtoMessage() {}

func (x *DeleteDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDeviceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeviceResponse) Reset() {
	*x = DeleteDeviceResponse{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeviceResponse) ProtoMessage() {}

func (x *DeleteDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeviceResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDeviceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TypeFilter    DeviceType             `protobuf:"varint,3,opt,name=type_filter,json=typeFilter,proto3,enum=manage_info.v1.DeviceType" json:"type_filter,omitempty"`
	StatusFilter  DeviceStatus           `protobuf:"varint,4,opt,name=status_filter,json=statusFilter,proto3,enum=manage_info.v1.DeviceStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{9}
}

func (x *ListDevicesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDevicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDevicesRequest) GetTypeFilter() DeviceType {
	if x != nil {
		return x.TypeFilter
	}
	return DeviceType_DEVICE_TYPE_UNKNOWN
}

func (x *ListDevicesRequest) GetStatusFilter() DeviceStatus {
	if x != nil {
		return x.StatusFilter
	}
	return DeviceStatus_DEVICE_STATUS_UNKNOWN
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{10}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ListDevicesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDevicesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDevicesResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{11}
}

type DeviceGroupSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Online        int32                  `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Offline       int32                  `protobuf:"varint,3,opt,name=offline,proto3" json:"offline,omitempty"`
	Maintenance   int32                  `protobuf:"varint,4,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceGroupSummary) Reset() {
	*x = DeviceGroupSummary{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceGroupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceGroupSummary) ProtoMessage() {}

func (x *DeviceGroupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceGroupSummary.ProtoReflect.Descriptor instead.
func (*DeviceGroupSummary) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{12}
}

func (x *DeviceGroupSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DeviceGroupSummary) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *DeviceGroupSummary) GetOffline() int32 {
	if x != nil {
		return x.Offline
	}
	return 0
}

func (x *DeviceGroupSummary) GetMaintenance() int32 {
	if x != nil {
		return x.Maintenance
	}
	return 0
}

// Trả về 3 nhóm riêng biệt: radar, tdoa, hub
type ManageInfoSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radar         *DeviceGroupSummary    `protobuf:"bytes,1,opt,name=radar,proto3" json:"radar,omitempty"`
	Tdoa          *DeviceGroupSummary    `protobuf:"bytes,2,opt,name=tdoa,proto3" json:"tdoa,omitempty"`
	Hub           *DeviceGroupSummary    `protobuf:"bytes,3,opt,name=hub,proto3" json:"hub,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManageInfoSummary) Reset() {
	*x = ManageInfoSummary{}
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManageInfoSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageInfoSummary) ProtoMessage() {}

func (x *ManageInfoSummary) ProtoReflect() protoreflect.Message {
	mi := &file_manage_info_v1_manage_info_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageInfoSummary.ProtoReflect.Descriptor instead.
func (*ManageInfoSummary) Descriptor() ([]byte, []int) {
	return file_manage_info_v1_manage_info_proto_rawDescGZIP(), []int{13}
}

func (x *ManageInfoSummary) GetRadar() *DeviceGroupSummary {
	if x != nil {
		return x.Radar
	}
	return nil
}

func (x *ManageInfoSummary) GetTdoa() *DeviceGroupSummary {
	if x != nil {
		return x.Tdoa
	}
	return nil
}

func (x *ManageInfoSummary) GetHub() *DeviceGroupSummary {
	if x != nil {
		return x.Hub
	}
	return nil
}

var File_manage_info_v1_manage_info_proto protoreflect.FileDescriptor

const file_manage_info_v1_manage_info_proto_rawDesc = "" +
	"\n" +
	" manage_info/v1/manage_info.proto\x12\x0emanage_info.v1\"\xa4\x02\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12.\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.manage_info.v1.DeviceTypeR\x04type\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x06 \x01(\tR\aaddress\x124\n" +
	"\x06status\x18\a \x01(\x0e2\x1c.manage_info.v1.DeviceStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\xad\x01\n" +
	"\x13CreateDeviceRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.manage_info.v1.DeviceTypeR\x04type\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\"F\n" +
	"\x14CreateDeviceResponse\x12.\n" +
	"\x06device\x18\x01 \x01(\v2\x16.manage_info.v1.DeviceR\x06device\"\"\n" +
	"\x10GetDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x11GetDeviceResponse\x12.\n" +
	"\x06device\x18\x01 \x01(\v2\x16.manage_info.v1.DeviceR\x06device\"\xc3\x01\n" +
	"\x13UpdateDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x124\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1c.manage_info.v1.DeviceStatusR\x06status\"F\n" +
	"\x14UpdateDeviceResponse\x12.\n" +
	"\x06device\x18\x01 \x01(\v2\x16.manage_info.v1.DeviceR\x06device\"%\n" +
	"\x13DeleteDeviceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x14DeleteDeviceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc5\x01\n" +
	"\x12ListDevicesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12;\n" +
	"\vtype_filter\x18\x03 \x01(\x0e2\x1a.manage_info.v1.DeviceTypeR\n" +
	"typeFilter\x12A\n" +
	"\rstatus_filter\x18\x04 \x01(\x0e2\x1c.manage_info.v1.DeviceStatusR\fstatusFilter\"\x8e\x01\n" +
	"\x13ListDevicesResponse\x120\n" +
	"\adevices\x18\x01 \x03(\v2\x16.manage_info.v1.DeviceR\adevices\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x13\n" +
	"\x11GetSummaryRequest\"~\n" +
	"\x12DeviceGroupSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06online\x18\x02 \x01(\x05R\x06online\x12\x18\n" +
	"\aoffline\x18\x03 \x01(\x05R\aoffline\x12 \n" +
	"\vmaintenance\x18\x04 \x01(\x05R\vmaintenance\"\xbb\x01\n" +
	"\x11ManageInfoSummary\x128\n" +
	"\x05radar\x18\x01 \x01(\v2\".manage_info.v1.DeviceGroupSummaryR\x05radar\x126\n" +
	"\x04tdoa\x18\x02 \x01(\v2\".manage_info.v1.DeviceGroupSummaryR\x04tdoa\x124\n" +
	"\x03hub\x18\x03 \x01(\v2\".manage_info.v1.DeviceGroupSummaryR\x03hub*g\n" +
	"\n" +
	"DeviceType\x12\x17\n" +
	"\x13DEVICE_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11DEVICE_TYPE_RADAR\x10\x01\x12\x14\n" +
	"\x10DEVICE_TYPE_TDOA\x10\x02\x12\x13\n" +
	"\x0fDEVICE_TYPE_HUB\x10\x03*}\n" +
	"\fDeviceStatus\x12\x19\n" +
	"\x15DEVICE_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14DEVICE_STATUS_ONLINE\x10\x01\x12\x19\n" +
	"\x15DEVICE_STATUS_OFFLINE\x10\x02\x12\x1d\n" +
	"\x19DEVICE_STATUS_MAINTENANCE\x10\x032\xa2\x04\n" +
	"\x11ManageInfoService\x12Y\n" +
	"\fCreateDevice\x12#.manage_info.v1.CreateDeviceRequest\x1a$.manage_info.v1.CreateDeviceResponse\x12P\n" +
	"\tGetDevice\x12 .manage_info.v1.GetDeviceRequest\x1a!.manage_info.v1.GetDeviceResponse\x12Y\n" +
	"\fUpdateDevice\x12#.manage_info.v1.UpdateDeviceRequest\x1a$.manage_info.v1.UpdateDeviceResponse\x12Y\n" +
	"\fDeleteDevice\x12#.manage_info.v1.DeleteDeviceRequest\x1a$.manage_info.v1.DeleteDeviceResponse\x12V\n" +
	"\vListDevices\x12\".manage_info.v1.ListDevicesRequest\x1a#.manage_info.v1.ListDevicesResponse\x12R\n" +
	"\n" +
	"GetSummary\x12!.manage_info.v1.GetSummaryRequest\x1a!.manage_info.v1.ManageInfoSummaryB)Z'github.com/utm/station-mgmt/pkg/pb/mipbb\x06proto3"

var (
	file_manage_info_v1_manage_info_proto_rawDescOnce sync.Once
	file_manage_info_v1_manage_info_proto_rawDescData []byte
)

func file_manage_info_v1_manage_info_proto_rawDescGZIP() []byte {
	file_manage_info_v1_manage_info_proto_rawDescOnce.Do(func() {
		file_manage_info_v1_manage_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manage_info_v1_manage_info_proto_rawDesc), len(file_manage_info_v1_manage_info_proto_rawDesc)))
	})
	return file_manage_info_v1_manage_info_proto_rawDescData
}

var file_manage_info_v1_manage_info_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_manage_info_v1_manage_info_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_manage_info_v1_manage_info_proto_goTypes = []any{
	(DeviceType)(0),              // 0: manage_info.v1.DeviceType
	(DeviceStatus)(0),            // 1: manage_info.v1.DeviceStatus
	(*Device)(nil),               // 2: manage_info.v1.Device
	(*CreateDeviceRequest)(nil),  // 3: manage_info.v1.CreateDeviceRequest
	(*CreateDeviceResponse)(nil), // 4: manage_info.v1.CreateDeviceResponse
	(*GetDeviceRequest)(nil),     // 5: manage_info.v1.GetDeviceRequest
	(*GetDeviceResponse)(nil),    // 6: manage_info.v1.GetDeviceResponse
	(*UpdateDeviceRequest)(nil),  // 7: manage_info.v1.UpdateDeviceRequest
	(*UpdateDeviceResponse)(nil), // 8: manage_info.v1.UpdateDeviceResponse
	(*DeleteDeviceRequest)(nil),  // 9: manage_info.v1.DeleteDeviceRequest
	(*DeleteDeviceResponse)(nil), // 10: manage_info.v1.DeleteDeviceResponse
	(*ListDevicesRequest)(nil),   // 11: manage_info.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),  // 12: manage_info.v1.ListDevicesResponse
	(*GetSummaryRequest)(nil),    // 13: manage_info.v1.GetSummaryRequest
	(*DeviceGroupSummary)(nil),   // 14: manage_info.v1.DeviceGroupSummary
	(*ManageInfoSummary)(nil),    // 15: manage_info.v1.ManageInfoSummary
}
var file_manage_info_v1_manage_info_proto_depIdxs = []int32{
	0,  // 0: manage_info.v1.Device.type:type_name -> manage_info.v1.DeviceType
	1,  // 1: manage_info.v1.Device.status:type_name -> manage_info.v1.DeviceStatus
	0,  // 2: manage_info.v1.CreateDeviceRequest.type:type_name -> manage_info.v1.DeviceType
	2,  // 3: manage_info.v1.CreateDeviceResponse.device:type_name -> manage_info.v1.Device
	2,  // 4: manage_info.v1.GetDeviceResponse.device:type_name -> manage_info.v1.Device
	1,  // 5: manage_info.v1.UpdateDeviceRequest.status:type_name -> manage_info.v1.DeviceStatus
	2,  // 6: manage_info.v1.UpdateDeviceResponse.device:type_name -> manage_info.v1.Device
	0,  // 7: manage_info.v1.ListDevicesRequest.type_filter:type_name -> manage_info.v1.DeviceType
	1,  // 8: manage_info.v1.ListDevicesRequest.status_filter:type_name -> manage_info.v1.DeviceStatus
	2,  // 9: manage_info.v1.ListDevicesResponse.devices:type_name -> manage_info.v1.Device
	14, // 10: manage_info.v1.ManageInfoSummary.radar:type_name -> manage_info.v1.DeviceGroupSummary
	14, // 11: manage_info.v1.ManageInfoSummary.tdoa:type_name -> manage_info.v1.DeviceGroupSummary
	14, // 12: manage_info.v1.ManageInfoSummary.hub:type_name -> manage_info.v1.DeviceGroupSummary
	3,  // 13: manage_info.v1.ManageInfoService.CreateDevice:input_type -> manage_info.v1.CreateDeviceRequest
	5,  // 14: manage_info.v1.ManageInfoService.GetDevice:input_type -> manage_info.v1.GetDeviceRequest
	7,  // 15: manage_info.v1.ManageInfoService.UpdateDevice:input_type -> manage_info.v1.UpdateDeviceRequest
	9,  // 16: manage_info.v1.ManageInfoService.DeleteDevice:input_type -> manage_info.v1.DeleteDeviceRequest
	11, // 17: manage_info.v1.ManageInfoService.ListDevices:input_type -> manage_info.v1.ListDevicesRequest
	13, // 18: manage_info.v1.ManageInfoService.GetSummary:input_type -> manage_info.v1.GetSummaryRequest
	4,  // 19: manage_info.v1.ManageInfoService.CreateDevice:output_type -> manage_info.v1.CreateDeviceResponse
	6,  // 20: manage_info.v1.ManageInfoService.GetDevice:output_type -> manage_info.v1.GetDeviceResponse
	8,  // 21: manage_info.v1.ManageInfoService.UpdateDevice:output_type -> manage_info.v1.UpdateDeviceResponse
	10, // 22: manage_info.v1.ManageInfoService.DeleteDevice:output_type -> manage_info.v1.DeleteDeviceResponse
	12, // 23: manage_info.v1.ManageInfoService.ListDevices:output_type -> manage_info.v1.ListDevicesResponse
	15, // 24: manage_info.v1.ManageInfoService.GetSummary:output_type -> manage_info.v1.ManageInfoSummary
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_manage_info_v1_manage_info_proto_init() }
func file_manage_info_v1_manage_info_proto_init() {
	if File_manage_info_v1_manage_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manage_info_v1_manage_info_proto_rawDesc), len(file_manage_info_v1_manage_info_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manage_info_v1_manage_info_proto_goTypes,
		DependencyIndexes: file_manage_info_v1_manage_info_proto_depIdxs,
		EnumInfos:         file_manage_info_v1_manage_info_proto_enumTypes,
		MessageInfos:      file_manage_info_v1_manage_info_proto_msgTypes,
	}.Build()
	File_manage_info_v1_manage_info_proto = out.File
	file_manage_info_v1_manage_info_proto_goTypes = nil
	file_manage_info_v1_manage_info_proto_depIdxs = nil
}
