// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: network_station/v1/network_station.proto

package nspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NetworkStationService_CreateStation_FullMethodName = "/network_station.v1.NetworkStationService/CreateStation"
	NetworkStationService_GetStation_FullMethodName    = "/network_station.v1.NetworkStationService/GetStation"
	NetworkStationService_UpdateStation_FullMethodName = "/network_station.v1.NetworkStationService/UpdateStation"
	NetworkStationService_DeleteStation_FullMethodName = "/network_station.v1.NetworkStationService/DeleteStation"
	NetworkStationService_ListStations_FullMethodName  = "/network_station.v1.NetworkStationService/ListStations"
	NetworkStationService_GetSummary_FullMethodName    = "/network_station.v1.NetworkStationService/GetSummary"
)

// NetworkStationServiceClient is the client API for NetworkStationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkStationServiceClient interface {
	CreateStation(ctx context.Context, in *CreateStationRequest, opts ...grpc.CallOption) (*CreateStationResponse, error)
	GetStation(ctx context.Context, in *GetStationRequest, opts ...grpc.CallOption) (*GetStationResponse, error)
	UpdateStation(ctx context.Context, in *UpdateStationRequest, opts ...grpc.CallOption) (*UpdateStationResponse, error)
	DeleteStation(ctx context.Context, in *DeleteStationRequest, opts ...grpc.CallOption) (*DeleteStationResponse, error)
	ListStations(ctx context.Context, in *ListStationsRequest, opts ...grpc.CallOption) (*ListStationsResponse, error)
	GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*StationSummary, error)
}

type networkStationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkStationServiceClient(cc grpc.ClientConnInterface) NetworkStationServiceClient {
	return &networkStationServiceClient{cc}
}

func (c *networkStationServiceClient) CreateStation(ctx context.Context, in *CreateStationRequest, opts ...grpc.CallOption) (*CreateStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStationResponse)
	err := c.cc.Invoke(ctx, NetworkStationService_CreateStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkStationServiceClient) GetStation(ctx context.Context, in *GetStationRequest, opts ...grpc.CallOption) (*GetStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStationResponse)
	err := c.cc.Invoke(ctx, NetworkStationService_GetStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkStationServiceClient) UpdateStation(ctx context.Context, in *UpdateStationRequest, opts ...grpc.CallOption) (*UpdateStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStationResponse)
	err := c.cc.Invoke(ctx, NetworkStationService_UpdateStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkStationServiceClient) DeleteStation(ctx context.Context, in *DeleteStationRequest, opts ...grpc.CallOption) (*DeleteStationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStationResponse)
	err := c.cc.Invoke(ctx, NetworkStationService_DeleteStation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkStationServiceClient) ListStations(ctx context.Context, in *ListStationsRequest, opts ...grpc.CallOption) (*ListStationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStationsResponse)
	err := c.cc.Invoke(ctx, NetworkStationService_ListStations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *networkStationServiceClient) GetSummary(ctx context.Context, in *GetSummaryRequest, opts ...grpc.CallOption) (*StationSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StationSummary)
	err := c.cc.Invoke(ctx, NetworkStationService_GetSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetworkStationServiceServer is the server API for NetworkStationService service.
// All implementations must embed UnimplementedNetworkStationServiceServer
// for forward compatibility.
type NetworkStationServiceServer interface {
	CreateStation(context.Context, *CreateStationRequest) (*CreateStationResponse, error)
	GetStation(context.Context, *GetStationRequest) (*GetStationResponse, error)
	UpdateStation(context.Context, *UpdateStationRequest) (*UpdateStationResponse, error)
	DeleteStation(context.Context, *DeleteStationRequest) (*DeleteStationResponse, error)
	ListStations(context.Context, *ListStationsRequest) (*ListStationsResponse, error)
	GetSummary(context.Context, *GetSummaryRequest) (*StationSummary, error)
	mustEmbedUnimplementedNetworkStationServiceServer()
}

// UnimplementedNetworkStationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkStationServiceServer struct{}

func (UnimplementedNetworkStationServiceServer) CreateStation(context.Context, *CreateStationRequest) (*CreateStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStation not implemented")
}
func (UnimplementedNetworkStationServiceServer) GetStation(context.Context, *GetStationRequest) (*GetStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStation not implemented")
}
func (UnimplementedNetworkStationServiceServer) UpdateStation(context.Context, *UpdateStationRequest) (*UpdateStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStation not implemented")
}
func (UnimplementedNetworkStationServiceServer) DeleteStation(context.Context, *DeleteStationRequest) (*DeleteStationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStation not implemented")
}
func (UnimplementedNetworkStationServiceServer) ListStations(context.Context, *ListStationsRequest) (*ListStationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStations not implemented")
}
func (UnimplementedNetworkStationServiceServer) GetSummary(context.Context, *GetSummaryRequest) (*StationSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSummary not implemented")
}
func (UnimplementedNetworkStationServiceServer) mustEmbedUnimplementedNetworkStationServiceServer() {}
func (UnimplementedNetworkStationServiceServer) testEmbeddedByValue()                               {}

// UnsafeNetworkStationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkStationServiceServer will
// result in compilation errors.
type UnsafeNetworkStationServiceServer interface {
	mustEmbedUnimplementedNetworkStationServiceServer()
}

func RegisterNetworkStationServiceServer(s grpc.ServiceRegistrar, srv NetworkStationServiceServer) {
	// If the following call panics, it indicates UnimplementedNetworkStationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkStationService_ServiceDesc, srv)
}

func _NetworkStationService_CreateStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkStationServiceServer).CreateStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkStationService_CreateStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkStationServiceServer).CreateStation(ctx, req.(*CreateStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkStationService_GetStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkStationServiceServer).GetStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkStationService_GetStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkStationServiceServer).GetStation(ctx, req.(*GetStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkStationService_UpdateStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkStationServiceServer).UpdateStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkStationService_UpdateStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkStationServiceServer).UpdateStation(ctx, req.(*UpdateStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkStationService_DeleteStation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkStationServiceServer).DeleteStation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkStationService_DeleteStation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkStationServiceServer).DeleteStation(ctx, req.(*DeleteStationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkStationService_ListStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkStationServiceServer).ListStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkStationService_ListStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkStationServiceServer).ListStations(ctx, req.(*ListStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NetworkStationService_GetSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetworkStationServiceServer).GetSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NetworkStationService_GetSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetworkStationServiceServer).GetSummary(ctx, req.(*GetSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetworkStationService_ServiceDesc is the grpc.ServiceDesc for NetworkStationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkStationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network_station.v1.NetworkStationService",
	HandlerType: (*NetworkStationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStation",
			Handler:    _NetworkStationService_CreateStation_Handler,
		},
		{
			MethodName: "GetStation",
			Handler:    _NetworkStationService_GetStation_Handler,
		},
		{
			MethodName: "UpdateStation",
			Handler:    _NetworkStationService_UpdateStation_Handler,
		},
		{
			MethodName: "DeleteStation",
			Handler:    _NetworkStationService_DeleteStation_Handler,
		},
		{
			MethodName: "ListStations",
			Handler:    _NetworkStationService_ListStations_Handler,
		},
		{
			MethodName: "GetSummary",
			Handler:    _NetworkStationService_GetSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network_station/v1/network_station.proto",
}
