// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: network_station/v1/network_station.proto

package nspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StationStatus int32

const (
	StationStatus_STATION_STATUS_UNKNOWN     StationStatus = 0
	StationStatus_STATION_STATUS_ONLINE      StationStatus = 1
	StationStatus_STATION_STATUS_OFFLINE     StationStatus = 2
	StationStatus_STATION_STATUS_MAINTENANCE StationStatus = 3
)

// Enum value maps for StationStatus.
var (
	StationStatus_name = map[int32]string{
		0: "STATION_STATUS_UNKNOWN",
		1: "STATION_STATUS_ONLINE",
		2: "STATION_STATUS_OFFLINE",
		3: "STATION_STATUS_MAINTENANCE",
	}
	StationStatus_value = map[string]int32{
		"STATION_STATUS_UNKNOWN":     0,
		"STATION_STATUS_ONLINE":      1,
		"STATION_STATUS_OFFLINE":     2,
		"STATION_STATUS_MAINTENANCE": 3,
	}
)

func (x StationStatus) Enum() *StationStatus {
	p := new(StationStatus)
	*p = x
	return p
}

func (x StationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_network_station_v1_network_station_proto_enumTypes[0].Descriptor()
}

func (StationStatus) Type() protoreflect.EnumType {
	return &file_network_station_v1_network_station_proto_enumTypes[0]
}

func (x StationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StationStatus.Descriptor instead.
func (StationStatus) EnumDescriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{0}
}

type NetworkStation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude         float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address          string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Status           StationStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=network_station.v1.StationStatus" json:"status,omitempty"`
	Operator         string                 `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`                                // nhà mạng
	FrequencyBand    string                 `protobuf:"bytes,8,opt,name=frequency_band,json=frequencyBand,proto3" json:"frequency_band,omitempty"` // băng tần (e.g. "n78", "n41")
	CoverageRadiusKm float64                `protobuf:"fixed64,9,opt,name=coverage_radius_km,json=coverageRadiusKm,proto3" json:"coverage_radius_km,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // unix millis
	UpdatedAt        int64                  `protobuf:"varint,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkStation) Reset() {
	*x = NetworkStation{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStation) ProtoMessage() {}

func (x *NetworkStation) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStation.ProtoReflect.Descriptor instead.
func (*NetworkStation) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{0}
}

func (x *NetworkStation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NetworkStation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkStation) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *NetworkStation) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *NetworkStation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NetworkStation) GetStatus() StationStatus {
	if x != nil {
		return x.Status
	}
	return StationStatus_STATION_STATUS_UNKNOWN
}

func (x *NetworkStation) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *NetworkStation) GetFrequencyBand() string {
	if x != nil {
		return x.FrequencyBand
	}
	return ""
}

func (x *NetworkStation) GetCoverageRadiusKm() float64 {
	if x != nil {
		return x.CoverageRadiusKm
	}
	return 0
}

func (x *NetworkStation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *NetworkStation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateStationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude         float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address          string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Operator         string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	FrequencyBand    string                 `protobuf:"bytes,6,opt,name=frequency_band,json=frequencyBand,proto3" json:"frequency_band,omitempty"`
	CoverageRadiusKm float64                `protobuf:"fixed64,7,opt,name=coverage_radius_km,json=coverageRadiusKm,proto3" json:"coverage_radius_km,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateStationRequest) Reset() {
	*x = CreateStationRequest{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStationRequest) ProtoMessage() {}

func (x *CreateStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStationRequest.ProtoReflect.Descriptor instead.
func (*CreateStationRequest) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CreateStationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CreateStationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateStationRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *CreateStationRequest) GetFrequencyBand() string {
	if x != nil {
		return x.FrequencyBand
	}
	return ""
}

func (x *CreateStationRequest) GetCoverageRadiusKm() float64 {
	if x != nil {
		return x.CoverageRadiusKm
	}
	return 0
}

type CreateStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Station       *NetworkStation        `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStationResponse) Reset() {
	*x = CreateStationResponse{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStationResponse) ProtoMessage() {}

func (x *CreateStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStationResponse.ProtoReflect.Descriptor instead.
func (*CreateStationResponse) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStationResponse) GetStation() *NetworkStation {
	if x != nil {
		return x.Station
	}
	return nil
}

type GetStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationRequest) Reset() {
	*x = GetStationRequest{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationRequest) ProtoMessage() {}

func (x *GetStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationRequest.ProtoReflect.Descriptor instead.
func (*GetStationRequest) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{3}
}

func (x *GetStationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Station       *NetworkStation        `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStationResponse) Reset() {
	*x = GetStationResponse{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStationResponse) ProtoMessage() {}

func (x *GetStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStationResponse.ProtoReflect.Descriptor instead.
func (*GetStationResponse) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{4}
}

func (x *GetStationResponse) GetStation() *NetworkStation {
	if x != nil {
		return x.Station
	}
	return nil
}

type UpdateStationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Latitude         float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude        float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address          string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Status           StationStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=network_station.v1.StationStatus" json:"status,omitempty"`
	Operator         string                 `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	FrequencyBand    string                 `protobuf:"bytes,8,opt,name=frequency_band,json=frequencyBand,proto3" json:"frequency_band,omitempty"`
	CoverageRadiusKm float64                `protobuf:"fixed64,9,opt,name=coverage_radius_km,json=coverageRadiusKm,proto3" json:"coverage_radius_km,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateStationRequest) Reset() {
	*x = UpdateStationRequest{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStationRequest) ProtoMessage() {}

func (x *UpdateStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStationRequest.ProtoReflect.Descriptor instead.
func (*UpdateStationRequest) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateStationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateStationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateStationRequest) GetStatus() StationStatus {
	if x != nil {
		return x.Status
	}
	return StationStatus_STATION_STATUS_UNKNOWN
}

func (x *UpdateStationRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *UpdateStationRequest) GetFrequencyBand() string {
	if x != nil {
		return x.FrequencyBand
	}
	return ""
}

func (x *UpdateStationRequest) GetCoverageRadiusKm() float64 {
	if x != nil {
		return x.CoverageRadiusKm
	}
	return 0
}

type UpdateStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Station       *NetworkStation        `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStationResponse) Reset() {
	*x = UpdateStationResponse{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStationResponse) ProtoMessage() {}

func (x *UpdateStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStationResponse.ProtoReflect.Descriptor instead.
func (*UpdateStationResponse) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStationResponse) GetStation() *NetworkStation {
	if x != nil {
		return x.Station
	}
	return nil
}

type DeleteStationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStationRequest) Reset() {
	*x = DeleteStationRequest{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStationRequest) ProtoMessage() {}

func (x *DeleteStationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStationRequest.ProtoReflect.Descriptor instead.
func (*DeleteStationRequest) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteStationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteStationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStationResponse) Reset() {
	*x = DeleteStationResponse{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStationResponse) ProtoMessage() {}

func (x *DeleteStationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStationResponse.ProtoReflect.Descriptor instead.
func (*DeleteStationResponse) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteStationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListStationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	StatusFilter  StationStatus          `protobuf:"varint,3,opt,name=status_filter,json=statusFilter,proto3,enum=network_station.v1.StationStatus" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStationsRequest) Reset() {
	*x = ListStationsRequest{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStationsRequest) ProtoMessage() {}

func (x *ListStationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStationsRequest.ProtoReflect.Descriptor instead.
func (*ListStationsRequest) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{9}
}

func (x *ListStationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStationsRequest) GetStatusFilter() StationStatus {
	if x != nil {
		return x.StatusFilter
	}
	return StationStatus_STATION_STATUS_UNKNOWN
}

type ListStationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stations      []*NetworkStation      `protobuf:"bytes,1,rep,name=stations,proto3" json:"stations,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStationsResponse) Reset() {
	*x = ListStationsResponse{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStationsResponse) ProtoMessage() {}

func (x *ListStationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStationsResponse.ProtoReflect.Descriptor instead.
func (*ListStationsResponse) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{10}
}

func (x *ListStationsResponse) GetStations() []*NetworkStation {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *ListStationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListStationsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStationsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{11}
}

type StationSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Online        int32                  `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Offline       int32                  `protobuf:"varint,3,opt,name=offline,proto3" json:"offline,omitempty"`
	Maintenance   int32                  `protobuf:"varint,4,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationSummary) Reset() {
	*x = StationSummary{}
	mi := &file_network_station_v1_network_station_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationSummary) ProtoMessage() {}

func (x *StationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_network_station_v1_network_station_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationSummary.ProtoReflect.Descriptor instead.
func (*StationSummary) Descriptor() ([]byte, []int) {
	return file_network_station_v1_network_station_proto_rawDescGZIP(), []int{12}
}

func (x *StationSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StationSummary) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *StationSummary) GetOffline() int32 {
	if x != nil {
		return x.Offline
	}
	return 0
}

func (x *StationSummary) GetMaintenance() int32 {
	if x != nil {
		return x.Maintenance
	}
	return 0
}

var File_network_station_v1_network_station_proto protoreflect.FileDescriptor

const file_network_station_v1_network_station_proto_rawDesc = "" +
	"\n" +
	"(network_station/v1/network_station.proto\x12\x12network_station.v1\"\xf2\x02\n" +
	"\x0eNetworkStation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.network_station.v1.StationStatusR\x06status\x12\x1a\n" +
	"\boperator\x18\a \x01(\tR\boperator\x12%\n" +
	"\x0efrequency_band\x18\b \x01(\tR\rfrequencyBand\x12,\n" +
	"\x12coverage_radius_km\x18\t \x01(\x01R\x10coverageRadiusKm\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\v \x01(\x03R\tupdatedAt\"\xef\x01\n" +
	"\x14CreateStationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12%\n" +
	"\x0efrequency_band\x18\x06 \x01(\tR\rfrequencyBand\x12,\n" +
	"\x12coverage_radius_km\x18\a \x01(\x01R\x10coverageRadiusKm\"U\n" +
	"\x15CreateStationResponse\x12<\n" +
	"\astation\x18\x01 \x01(\v2\".network_station.v1.NetworkStationR\astation\"#\n" +
	"\x11GetStationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x12GetStationResponse\x12<\n" +
	"\astation\x18\x01 \x01(\v2\".network_station.v1.NetworkStationR\astation\"\xba\x02\n" +
	"\x14UpdateStationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x129\n" +
	"\x06status\x18\x06 \x01(\x0e2!.network_station.v1.StationStatusR\x06status\x12\x1a\n" +
	"\boperator\x18\a \x01(\tR\boperator\x12%\n" +
	"\x0efrequency_band\x18\b \x01(\tR\rfrequencyBand\x12,\n" +
	"\x12coverage_radius_km\x18\t \x01(\x01R\x10coverageRadiusKm\"U\n" +
	"\x15UpdateStationResponse\x12<\n" +
	"\astation\x18\x01 \x01(\v2\".network_station.v1.NetworkStationR\astation\"&\n" +
	"\x14DeleteStationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x15DeleteStationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x01\n" +
	"\x13ListStationsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12F\n" +
	"\rstatus_filter\x18\x03 \x01(\x0e2!.network_station.v1.StationStatusR\fstatusFilter\"\x9d\x01\n" +
	"\x14ListStationsResponse\x12>\n" +
	"\bstations\x18\x01 \x03(\v2\".network_station.v1.NetworkStationR\bstations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x13\n" +
	"\x11GetSummaryRequest\"z\n" +
	"\x0eStationSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06online\x18\x02 \x01(\x05R\x06online\x12\x18\n" +
	"\aoffline\x18\x03 \x01(\x05R\aoffline\x12 \n" +
	"\vmaintenance\x18\x04 \x01(\x05R\vmaintenance*\x82\x01\n" +
	"\rStationStatus\x12\x1a\n" +
	"\x16STATION_STATUS_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15STATION_STATUS_ONLINE\x10\x01\x12\x1a\n" +
	"\x16STATION_STATUS_OFFLINE\x10\x02\x12\x1e\n" +
	"\x1aSTATION_STATUS_MAINTENANCE\x10\x032\xe2\x04\n" +
	"\x15NetworkStationService\x12d\n" +
	"\rCreateStation\x12(.network_station.v1.CreateStationRequest\x1a).network_station.v1.CreateStationResponse\x12[\n" +
	"\n" +
	"GetStation\x12%.network_station.v1.GetStationRequest\x1a&.network_station.v1.GetStationResponse\x12d\n" +
	"\rUpdateStation\x12(.network_station.v1.UpdateStationRequest\x1a).network_station.v1.UpdateStationResponse\x12d\n" +
	"\rDeleteStation\x12(.network_station.v1.DeleteStationRequest\x1a).network_station.v1.DeleteStationResponse\x12a\n" +
	"\fListStations\x12'.network_station.v1.ListStationsRequest\x1a(.network_station.v1.ListStationsResponse\x12W\n" +
	"\n" +
	"GetSummary\x12%.network_station.v1.GetSummaryRequest\x1a\".network_station.v1.StationSummaryB)Z'github.com/utm/station-mgmt/pkg/pb/nspbb\x06proto3"

var (
	file_network_station_v1_network_station_proto_rawDescOnce sync.Once
	file_network_station_v1_network_station_proto_rawDescData []byte
)

func file_network_station_v1_network_station_proto_rawDescGZIP() []byte {
	file_network_station_v1_network_station_proto_rawDescOnce.Do(func() {
		file_network_station_v1_network_station_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_station_v1_network_station_proto_rawDesc), len(file_network_station_v1_network_station_proto_rawDesc)))
	})
	return file_network_station_v1_network_station_proto_rawDescData
}

var file_network_station_v1_network_station_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_network_station_v1_network_station_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_network_station_v1_network_station_proto_goTypes = []any{
	(StationStatus)(0),            // 0: network_station.v1.StationStatus
	(*NetworkStation)(nil),        // 1: network_station.v1.NetworkStation
	(*CreateStationRequest)(nil),  // 2: network_station.v1.CreateStationRequest
	(*CreateStationResponse)(nil), // 3: network_station.v1.CreateStationResponse
	(*GetStationRequest)(nil),     // 4: network_station.v1.GetStationRequest
	(*GetStationResponse)(nil),    // 5: network_station.v1.GetStationResponse
	(*UpdateStationRequest)(nil),  // 6: network_station.v1.UpdateStationRequest
	(*UpdateStationResponse)(nil), // 7: network_station.v1.UpdateStationResponse
	(*DeleteStationRequest)(nil),  // 8: network_station.v1.DeleteStationRequest
	(*DeleteStationResponse)(nil), // 9: network_station.v1.DeleteStationResponse
	(*ListStationsRequest)(nil),   // 10: network_station.v1.ListStationsRequest
	(*ListStationsResponse)(nil),  // 11: network_station.v1.ListStationsResponse
	(*GetSummaryRequest)(nil),     // 12: network_station.v1.GetSummaryRequest
	(*StationSummary)(nil),        // 13: network_station.v1.StationSummary
}
var file_network_station_v1_network_station_proto_depIdxs = []int32{
	0,  // 0: network_station.v1.NetworkStation.status:type_name -> network_station.v1.StationStatus
	1,  // 1: network_station.v1.CreateStationResponse.station:type_name -> network_station.v1.NetworkStation
	1,  // 2: network_station.v1.GetStationResponse.station:type_name -> network_station.v1.NetworkStation
	0,  // 3: network_station.v1.UpdateStationRequest.status:type_name -> network_station.v1.StationStatus
	1,  // 4: network_station.v1.UpdateStationResponse.station:type_name -> network_station.v1.NetworkStation
	0,  // 5: network_station.v1.ListStationsRequest.status_filter:type_name -> network_station.v1.StationStatus
	1,  // 6: network_station.v1.ListStationsResponse.stations:type_name -> network_station.v1.NetworkStation
	2,  // 7: network_station.v1.NetworkStationService.CreateStation:input_type -> network_station.v1.CreateStationRequest
	4,  // 8: network_station.v1.NetworkStationService.GetStation:input_type -> network_station.v1.GetStationRequest
	6,  // 9: network_station.v1.NetworkStationService.UpdateStation:input_type -> network_station.v1.UpdateStationRequest
	8,  // 10: network_station.v1.NetworkStationService.DeleteStation:input_type -> network_station.v1.DeleteStationRequest
	10, // 11: network_station.v1.NetworkStationService.ListStations:input_type -> network_station.v1.ListStationsRequest
	12, // 12: network_station.v1.NetworkStationService.GetSummary:input_type -> network_station.v1.GetSummaryRequest
	3,  // 13: network_station.v1.NetworkStationService.CreateStation:output_type -> network_station.v1.CreateStationResponse
	5,  // 14: network_station.v1.NetworkStationService.GetStation:output_type -> network_station.v1.GetStationResponse
	7,  // 15: network_station.v1.NetworkStationService.UpdateStation:output_type -> network_station.v1.UpdateStationResponse
	9,  // 16: network_station.v1.NetworkStationService.DeleteStation:output_type -> network_station.v1.DeleteStationResponse
	11, // 17: network_station.v1.NetworkStationService.ListStations:output_type -> network_station.v1.ListStationsResponse
	13, // 18: network_station.v1.NetworkStationService.GetSummary:output_type -> network_station.v1.StationSummary
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_network_station_v1_network_station_proto_init() }
func file_network_station_v1_network_station_proto_init() {
	if File_network_station_v1_network_station_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_station_v1_network_station_proto_rawDesc), len(file_network_station_v1_network_station_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_station_v1_network_station_proto_goTypes,
		DependencyIndexes: file_network_station_v1_network_station_proto_depIdxs,
		EnumInfos:         file_network_station_v1_network_station_proto_enumTypes,
		MessageInfos:      file_network_station_v1_network_station_proto_msgTypes,
	}.Build()
	File_network_station_v1_network_station_proto = out.File
	file_network_station_v1_network_station_proto_goTypes = nil
	file_network_station_v1_network_station_proto_depIdxs = nil
}
