// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: station_mgmt/v1/station_mgmt.proto

package smpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GroupSummary dùng chung cho tất cả 5 loại trạm/thiết bị
type GroupSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Online        int32                  `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Offline       int32                  `protobuf:"varint,3,opt,name=offline,proto3" json:"offline,omitempty"`
	Maintenance   int32                  `protobuf:"varint,4,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSummary) Reset() {
	*x = GroupSummary{}
	mi := &file_station_mgmt_v1_station_mgmt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSummary) ProtoMessage() {}

func (x *GroupSummary) ProtoReflect() protoreflect.Message {
	mi := &file_station_mgmt_v1_station_mgmt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSummary.ProtoReflect.Descriptor instead.
func (*GroupSummary) Descriptor() ([]byte, []int) {
	return file_station_mgmt_v1_station_mgmt_proto_rawDescGZIP(), []int{0}
}

func (x *GroupSummary) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GroupSummary) GetOnline() int32 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *GroupSummary) GetOffline() int32 {
	if x != nil {
		return x.Offline
	}
	return 0
}

func (x *GroupSummary) GetMaintenance() int32 {
	if x != nil {
		return x.Maintenance
	}
	return 0
}

type GetOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewRequest) Reset() {
	*x = GetOverviewRequest{}
	mi := &file_station_mgmt_v1_station_mgmt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewRequest) ProtoMessage() {}

func (x *GetOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_station_mgmt_v1_station_mgmt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetOverviewRequest) Descriptor() ([]byte, []int) {
	return file_station_mgmt_v1_station_mgmt_proto_rawDescGZIP(), []int{1}
}

type OverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FiveG         *GroupSummary          `protobuf:"bytes,1,opt,name=five_g,json=fiveG,proto3" json:"five_g,omitempty"` // 5G (network station)
	Rtk           *GroupSummary          `protobuf:"bytes,2,opt,name=rtk,proto3" json:"rtk,omitempty"`
	Radar         *GroupSummary          `protobuf:"bytes,3,opt,name=radar,proto3" json:"radar,omitempty"`
	Tdoa          *GroupSummary          `protobuf:"bytes,4,opt,name=tdoa,proto3" json:"tdoa,omitempty"`
	Hub           *GroupSummary          `protobuf:"bytes,5,opt,name=hub,proto3" json:"hub,omitempty"`
	FetchedAt     int64                  `protobuf:"varint,6,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"` // unix millis, thời điểm lấy data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewResponse) Reset() {
	*x = OverviewResponse{}
	mi := &file_station_mgmt_v1_station_mgmt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewResponse) ProtoMessage() {}

func (x *OverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_station_mgmt_v1_station_mgmt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewResponse.ProtoReflect.Descriptor instead.
func (*OverviewResponse) Descriptor() ([]byte, []int) {
	return file_station_mgmt_v1_station_mgmt_proto_rawDescGZIP(), []int{2}
}

func (x *OverviewResponse) GetFiveG() *GroupSummary {
	if x != nil {
		return x.FiveG
	}
	return nil
}

func (x *OverviewResponse) GetRtk() *GroupSummary {
	if x != nil {
		return x.Rtk
	}
	return nil
}

func (x *OverviewResponse) GetRadar() *GroupSummary {
	if x != nil {
		return x.Radar
	}
	return nil
}

func (x *OverviewResponse) GetTdoa() *GroupSummary {
	if x != nil {
		return x.Tdoa
	}
	return nil
}

func (x *OverviewResponse) GetHub() *GroupSummary {
	if x != nil {
		return x.Hub
	}
	return nil
}

func (x *OverviewResponse) GetFetchedAt() int64 {
	if x != nil {
		return x.FetchedAt
	}
	return 0
}

var File_station_mgmt_v1_station_mgmt_proto protoreflect.FileDescriptor

const file_station_mgmt_v1_station_mgmt_proto_rawDesc = "" +
	"\n" +
	"\"station_mgmt/v1/station_mgmt.proto\x12\x0fstation_mgmt.v1\"x\n" +
	"\fGroupSummary\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06online\x18\x02 \x01(\x05R\x06online\x12\x18\n" +
	"\aoffline\x18\x03 \x01(\x05R\aoffline\x12 \n" +
	"\vmaintenance\x18\x04 \x01(\x05R\vmaintenance\"\x14\n" +
	"\x12GetOverviewRequest\"\xb1\x02\n" +
	"\x10OverviewResponse\x124\n" +
	"\x06five_g\x18\x01 \x01(\v2\x1d.station_mgmt.v1.GroupSummaryR\x05fiveG\x12/\n" +
	"\x03rtk\x18\x02 \x01(\v2\x1d.station_mgmt.v1.GroupSummaryR\x03rtk\x123\n" +
	"\x05radar\x18\x03 \x01(\v2\x1d.station_mgmt.v1.GroupSummaryR\x05radar\x121\n" +
	"\x04tdoa\x18\x04 \x01(\v2\x1d.station_mgmt.v1.GroupSummaryR\x04tdoa\x12/\n" +
	"\x03hub\x18\x05 \x01(\v2\x1d.station_mgmt.v1.GroupSummaryR\x03hub\x12\x1d\n" +
	"\n" +
	"fetched_at\x18\x06 \x01(\x03R\tfetchedAt2q\n" +
	"\x18StationManagementService\x12U\n" +
	"\vGetOverview\x12#.station_mgmt.v1.GetOverviewRequest\x1a!.station_mgmt.v1.OverviewResponseB)Z'github.com/utm/station-mgmt/pkg/pb/smpbb\x06proto3"

var (
	file_station_mgmt_v1_station_mgmt_proto_rawDescOnce sync.Once
	file_station_mgmt_v1_station_mgmt_proto_rawDescData []byte
)

func file_station_mgmt_v1_station_mgmt_proto_rawDescGZIP() []byte {
	file_station_mgmt_v1_station_mgmt_proto_rawDescOnce.Do(func() {
		file_station_mgmt_v1_station_mgmt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_station_mgmt_v1_station_mgmt_proto_rawDesc), len(file_station_mgmt_v1_station_mgmt_proto_rawDesc)))
	})
	return file_station_mgmt_v1_station_mgmt_proto_rawDescData
}

var file_station_mgmt_v1_station_mgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_station_mgmt_v1_station_mgmt_proto_goTypes = []any{
	(*GroupSummary)(nil),       // 0: station_mgmt.v1.GroupSummary
	(*GetOverviewRequest)(nil), // 1: station_mgmt.v1.GetOverviewRequest
	(*OverviewResponse)(nil),   // 2: station_mgmt.v1.OverviewResponse
}
var file_station_mgmt_v1_station_mgmt_proto_depIdxs = []int32{
	0, // 0: station_mgmt.v1.OverviewResponse.five_g:type_name -> station_mgmt.v1.GroupSummary
	0, // 1: station_mgmt.v1.OverviewResponse.rtk:type_name -> station_mgmt.v1.GroupSummary
	0, // 2: station_mgmt.v1.OverviewResponse.radar:type_name -> station_mgmt.v1.GroupSummary
	0, // 3: station_mgmt.v1.OverviewResponse.tdoa:type_name -> station_mgmt.v1.GroupSummary
	0, // 4: station_mgmt.v1.OverviewResponse.hub:type_name -> station_mgmt.v1.GroupSummary
	1, // 5: station_mgmt.v1.StationManagementService.GetOverview:input_type -> station_mgmt.v1.GetOverviewRequest
	2, // 6: station_mgmt.v1.StationManagementService.GetOverview:output_type -> station_mgmt.v1.OverviewResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_station_mgmt_v1_station_mgmt_proto_init() }
func file_station_mgmt_v1_station_mgmt_proto_init() {
	if File_station_mgmt_v1_station_mgmt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_station_mgmt_v1_station_mgmt_proto_rawDesc), len(file_station_mgmt_v1_station_mgmt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_station_mgmt_v1_station_mgmt_proto_goTypes,
		DependencyIndexes: file_station_mgmt_v1_station_mgmt_proto_depIdxs,
		MessageInfos:      file_station_mgmt_v1_station_mgmt_proto_msgTypes,
	}.Build()
	File_station_mgmt_v1_station_mgmt_proto = out.File
	file_station_mgmt_v1_station_mgmt_proto_goTypes = nil
	file_station_mgmt_v1_station_mgmt_proto_depIdxs = nil
}
