// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: station_mgmt/v1/station_mgmt.proto

package smpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StationManagementService_GetOverview_FullMethodName = "/station_mgmt.v1.StationManagementService/GetOverview"
)

// StationManagementServiceClient is the client API for StationManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StationManagementServiceClient interface {
	GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*OverviewResponse, error)
}

type stationManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStationManagementServiceClient(cc grpc.ClientConnInterface) StationManagementServiceClient {
	return &stationManagementServiceClient{cc}
}

func (c *stationManagementServiceClient) GetOverview(ctx context.Context, in *GetOverviewRequest, opts ...grpc.CallOption) (*OverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverviewResponse)
	err := c.cc.Invoke(ctx, StationManagementService_GetOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StationManagementServiceServer is the server API for StationManagementService service.
// All implementations must embed UnimplementedStationManagementServiceServer
// for forward compatibility.
type StationManagementServiceServer interface {
	GetOverview(context.Context, *GetOverviewRequest) (*OverviewResponse, error)
	mustEmbedUnimplementedStationManagementServiceServer()
}

// UnimplementedStationManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStationManagementServiceServer struct{}

func (UnimplementedStationManagementServiceServer) GetOverview(context.Context, *GetOverviewRequest) (*OverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverview not implemented")
}
func (UnimplementedStationManagementServiceServer) mustEmbedUnimplementedStationManagementServiceServer() {
}
func (UnimplementedStationManagementServiceServer) testEmbeddedByValue() {}

// UnsafeStationManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StationManagementServiceServer will
// result in compilation errors.
type UnsafeStationManagementServiceServer interface {
	mustEmbedUnimplementedStationManagementServiceServer()
}

func RegisterStationManagementServiceServer(s grpc.ServiceRegistrar, srv StationManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedStationManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StationManagementService_ServiceDesc, srv)
}

func _StationManagementService_GetOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StationManagementServiceServer).GetOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StationManagementService_GetOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StationManagementServiceServer).GetOverview(ctx, req.(*GetOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StationManagementService_ServiceDesc is the grpc.ServiceDesc for StationManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StationManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "station_mgmt.v1.StationManagementService",
	HandlerType: (*StationManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOverview",
			Handler:    _StationManagementService_GetOverview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "station_mgmt/v1/station_mgmt.proto",
}
